---
title: "Analysis of Vienna Night Run Results"
subtitle: "Data Cleaning"
author: "Alex"
date: "`r format(Sys.time(), '%d %B %Y, %H:%M:%S')`"
output: 
  html_document:
    df_print: paged
    toc: true
    number_sections: false
---

Read raw data and add column names.

```{r}
read_vnr_raw <- function(year) {
  path_to_raw <- paste0("data/raw/vnr-results-public-", year, ".txt")
  raw_data <- read.delim(path_to_raw, header = FALSE, na.strings = " ")
  raw_data <- raw_data[, -c(1, 9)] # Remove columns 1 (index) and 9 (NA)
  # Add column names
  names(raw_data) <- c("id", "name", "sex", "company", "mins_per_km", "km_per_hour", "time")
  return(raw_data)
  }
```

Calculate time attributes.

```{r}
calc_time <- function(results) {
  z <- results
  # Keep only times less than 60 min
  z <- z[sapply(strsplit(z$time, split = ":"), length) == 2, ]
  # Split minutes part from the rest
  time_split <- strsplit(z$time, split = ":")
  # Populate minutes column
  z$mins <- as.integer(sapply(time_split, `[[`, 1))
  z$rest <- sapply(time_split, `[[`, 2)
  # Split seconds from the tenths of second
  secs_split <- strsplit(z$rest, split = ",")
  # Populate seconds column
  z$secs <- as.integer(sapply(secs_split, `[[`, 1))
  # Populate tenth of seconds column
  z$tsecs <- as.integer(sapply(secs_split, `[[`, 2))
  # Calculate total time in seconds
  z$time_secs <- z$mins * 60 + z$secs + z$tsecs * 0.1
  # Calculate total time in minutes
  z$time_mins <- z$time_secs / 60
  # Calculate pace (seconds per km)
  z$secs_per_km_calc <- z$time_secs / 5
  return(z)
}
```

Fix categorical factors.

```{r}
fix_factors <- function(results) {
  z <- results
  # Fix sex
  z$sex <- ifelse(z$sex == "m", "m", 
                      ifelse(z$sex == "w", "f", NA)) |> 
  as.factor()
  # Convert company affiliation to boolean
  z$affiliated <- ifelse(is.na(z$company), FALSE, TRUE)
  return(z)
}
```

Confirm pace as (incorrectly) provided in the original dataset.

```{r}
conf_pace <- function(results) {
  z <- results
  # Round the calculated seconds per km to the lowest integer. This is 
  # technically incorrect, but it's how it's handled in the original data.
  z$secs_per_km_calc_floor <- floor(z$secs_per_km_calc)
  # Extract the seconds of the "seconds per km" pace
  z$pace_secs <- z$secs_per_km_calc_floor %% 60
  # Get the seconds of the "seconds per km" pace from the original data
  pace_split <- strsplit(z$mins_per_km, split = ":")
  z$pace_secs_orig <- as.integer(sapply(pace_split, `[[`, 2))
  ind <- which(z$pace_secs - z$pace_secs_orig != 0)
  confirmed <- if(length(ind) == 0) { TRUE } else { FALSE }
  return(confirmed)
}
```

To check a prticular year, run:

```{r}
# 2022 |> 
#     read_vnr_raw() |> 
#     calc_time() |>
#     fix_factors() |> 
#     conf_pace()
```

Calculate correct speed.

```{r}
correct_speed <- function(results) {
  z <- results
  z$km_per_hour <- 5 * 60 * 60 / z$time_secs
  return(z)
}
```

Keep only relevant columns.

```{r}
keep_cols <- function(results) {
  z <- results
  z <- z[, c("id", "sex", "affiliated", "time_secs")]
  return(z)
}
```

Save cleaned results.

```{r}
write_vnr_clean <- function(year) {
  results <- year |> 
    read_vnr_raw() |> 
    calc_time() |>
    fix_factors() |> 
    correct_speed() |> 
    keep_cols()
  path_to_clean <- paste0("data/interim/vnr-results-clean-", year)
  write.table(results, file = paste0(path_to_clean, ".csv"), 
              sep = ";", row.names = FALSE)
  saveRDS(results, file = paste0(path_to_clean, ".rds"))
  }
```

```{r}
write_vnr_clean(2022)
write_vnr_clean(2023)
write_vnr_clean(2024)
```
