---
title: "Analysis of Vienna Night Run Results"
subtitle: "Common runners"
author: "Alex"
date: "`r format(Sys.time(), '%d %B %Y, %H:%M:%S')`"
output: 
  html_document:
    df_print: paged
    toc: true
    number_sections: false
---

Read full data

```{r}
cols_to_keep <- c("name", "id", "sex", "company", "time_secs")
```

```{r}
read_full_data <- function(year) {
  z <- readRDS(paste0("data/raw/vnr-results-full-", year, ".rds"))
  z <- z[, cols_to_keep]
  return(z)
}
```

```{r}
vnr_2022 <- read_full_data(2022)
vnr_2023 <- read_full_data(2023)
vnr_2024 <- read_full_data(2024)
```

```{r}
fix_names <- function(x, year) {
  names(x)[names(x) != "name"] <- paste0(names(x)[names(x) != "name"], "_", year)
  return(x)
}
```

```{r}
vnr_2022 <- fix_names(vnr_2022, 2022)
vnr_2023 <- fix_names(vnr_2023, 2023)
vnr_2024 <- fix_names(vnr_2024, 2024)
```

```{r}
z1 <- merge(x = vnr_2022, y = vnr_2023, by = "name")
z <- merge(x = z1, y = vnr_2024, by = "name")

head(z)
```

uptohere

```{r}
z_sex = z[, c("name", "sex_2022", "sex_2023", "sex_2024")]
z_sex$sex_diff <- apply(z_sex[, c("sex_2022", "sex_2023", "sex_2024")], 1, function(x) length(unique(x)) != 1)
z_sex[z_sex$sex_diff, c("name", "sex_2022", "sex_2023", "sex_2024")]
```

```{r}
z_sex = z[, c("name", "company_2022", "company_2023", "company_2024")]
z_sex$sex_diff <- apply(z_sex[, c("company_2022", "company_2023", "company_2024")], 1, function(x) length(unique(x)) != 1)
z_sex[z_sex$sex_diff, c("name", "company_2022", "company_2023", "company_2024")]
```











