---
title: "Analysis of Vienna Night Run Results"
subtitle: "Data Preprocessing"
author: "Alex"
date: "`r format(Sys.time(), '%d %B %Y, %H:%M:%S')`"
output: 
  html_document:
    df_print: paged
    toc: true
    number_sections: false
---

Load packages.

```{r}
library(dplyr)
library(purrr)
```

Read raw data and add column names.

```{r}
read_vnr_raw <- function(year) {
  path_to_raw <- paste0("../raw/vnr-results-public-", year, ".txt")
  raw_data <- read.delim(path_to_raw, header = FALSE, na.strings = " ")
  raw_data <- raw_data[, -c(1, 9)] # Remove columns 1 (index) and 9 (NA)
  names(raw_data) <- c("id", "name", "sex", "company", "mins_per_km", "km_per_hour", "time")
  return(raw_data)
  }
```

```{r}
raw_results <- read_vnr_raw(2022)
# head(z)
```

Fix times.

```{r}
fix_times <- function(raw_results) {
  z <- raw_results
  # Keep only times less than 60 min
  z <- z[sapply(strsplit(z$time, split = ":"), length) == 2, ]
  # Split minutes from the rest
  time_split <- strsplit(z$time, split = ":")
  # Populate minutes column
  z$mins <- as.integer(sapply(time_split, `[[`, 1))
  z$rest <- sapply(time_split, `[[`, 2)
  # Split seconds from the tenths of second
  secs_split <- strsplit(z$rest, split = ",")
  # Populate seconds column
  z$secs <- as.integer(sapply(secs_split, `[[`, 1))
  # Populate tenth of seconds column
  z$tsecs <- as.integer(sapply(secs_split, `[[`, 2))
  return(z)
}
```

```{r}
raw_results <- fix_times(raw_results)
head(raw_results)
```

```{r}
calc_time <- function(raw_results) {
  z <- raw_results
  # Calculate total time in seconds
  z$time_secs <- z$mins * 60 + z$secs + z$tsecs * 0.1
  # Calculate total time in minutes
  z$time_mins <- z$time_secs / 60
  return(z)
}
```

```{r}
raw_results <- calc_time(raw_results)
head(raw_results)
```

```{r}
speed_split <- strsplit(raw_results$mins_per_km, split = ":")
raw_results$secs_per_km <- as.integer(sapply(speed_split, `[[`, 1)) * 60 + 
  as.integer(sapply(speed_split, `[[`, 2)) 
```

```{r}
raw_results$perf_diff <- raw_results$secs_per_km - raw_results$time_secs/5
```

```{r}
plot(raw_results$tsecs, raw_results$perf_diff)
```


